<?php
// Webmasterei Bingads Alle Pages Tracker
//  class Webmasterei_Bingads_Block_Pages extends Mage_Core_Block_Abstract
?>
<?php
$uetTag = $this->getUetTag();
$isActive = $this->getBingadsActive();
?>
<script>
    (function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"5441557"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");
</script>
<noscript>
    <img src="//bat.bing.com/action/0?ti=5441557&Ver=2" height="0" width="0" style="display:none; visibility: hidden;" />
</noscript>

<script>
    (function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[]
        ,f=function(){var o={ti:"<?php echo $uetTag; ?>"};
        o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")}
        ,n=d.createElement(t),n.src=r,n.async=1,n.onload=n
        .onreadystatechange=function()
    {var s=this.readyState;s
    &&s!=="loaded"&&
    s!=="complete"||(f(),n.onload=n.
        onreadystatechange=null)},i=
        d.getElementsByTagName(t)[0],i.
    parentNode.insertBefore(n,i)})(window,document,"script","
    //bat.bing.com/bat.js","uetq");
</script>

<noscript><img src="//bat.bing.com/action/0?ti=<?php echo $uetTag; ?>&
          Ver=2" height="0" width="0" style="display:none
          ; visibility: hidden;" />
</noscript>